import { existsSync, readFileSync } from "node:fs";
import { dirname, join, parse } from "node:path";
import { fileURLToPath } from "node:url";
import { resolveRepoRoot } from "../shared/repo-root.js";

export function kitPackageDir(packageRoot: string, name: string): string {
    return join(resolveRepoRoot(packageRoot), "packages", name);
}

/**
 * Resolve the directory that holds a kit's authoring metadata (`meta.json`,
 * `KIT_CONTEXT.md`) for the CLI to read at runtime. Two layouts exist:
 *
 * - **Monorepo (dev/build):** the live source at `<repoRoot>/packages/<name>/`.
 * - **Published CLI:** a snapshot bundled into the CLI package at
 *   `<packageRoot>/registry/kits/<name>/`, because the published tarball does
 *   **not** ship `packages/` (kits are separate npm packages). The snapshot is
 *   generated by `scripts/sync-kit-registry.mjs`.
 *
 * Prefers the live source when it exists (authoritative during development and
 * in tests), otherwise falls back to the bundled snapshot. When neither exists
 * the returned path simply won't resolve and the loaders degrade to `null`.
 */
export function kitMetaDir(packageRoot: string, name: string): string {
    const sourceDir = join(resolveRepoRoot(packageRoot), "packages", name);
    if (existsSync(sourceDir)) {
        return sourceDir;
    }
    return join(packageRoot, "registry", "kits", name);
}

function isCulletPackageRoot(dir: string): boolean {
    const packageJsonPath = join(dir, "package.json");
    const registryPath = join(dir, "registry", "index.json");

    if (!existsSync(packageJsonPath) || !existsSync(registryPath)) {
        return false;
    }

    try {
        const parsed = JSON.parse(readFileSync(packageJsonPath, "utf8")) as {
            name?: unknown;
        };

        return parsed.name === "cullet";
    } catch {
        return false;
    }
}

export function findCulletPackageRoot(fromMetaUrl: string): string {
    // O bundler move o corpo dos modulos para chunks na raiz de dist/,
    // entao a profundidade do `import.meta.url` em runtime nao e fixa.
    let dir = dirname(fileURLToPath(fromMetaUrl));
    const filesystemRoot = parse(dir).root;

    while (true) {
        if (isCulletPackageRoot(dir)) {
            return dir;
        }

        if (dir === filesystemRoot) break;
        dir = dirname(dir);
    }

    throw new Error(
        "Nao foi possivel localizar o package.json do cullet a partir do pacote.",
    );
}
